name: n_generator_full
description: N Generator - Legal Notice Generator (expanded scaffold)
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pdf: ^3.8.1
  printing: ^5.9.0
  path_provider: ^2.0.12
  sqflite: ^2.2.8+4
  path: ^1.8.3
  image_picker: ^0.8.7+5
  share_plus: ^6.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo_pragati.png
    - assets/logo_northernarc.png
    - assets/placeholder_client.png